### ISSUE TITLE
Requirment.txt and Requests

### ISSUE THREAD

**Issue by MasterblastR** [smilegodly/mewbot#54]
Could not find Requirement:
ERROR: Could not find a version that satisfies the requirement cffi==1.14.0
ERROR: No matching distribution found for cffi==1.14.0

Requests not found:
\mewbot-master\mewbot.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by smilegodly** [comment]
```py
pip install requests
```
:)
